config/routes.rb
LocalReceivingApp::Application.routes.draw do

  root :to => "people#index"

  match '/receive', :to => 'people#receive'
  match '/sentitems/get_statuses', :to => 'sent_items#get_statuses'

  match ':controller(/:action(/:id(.:format)))'

   
end

app/models/daemon.rb
class Daemon < ActiveRecord::Base
end

app/models/gammu.rb
class Gammu < ActiveRecord::Base
  set_table_name 'gammu'
end

app/models/hola.rb
class Hola < ActiveRecord::Base
end

app/models/inbox.rb
class Inbox < ActiveRecord::Base
  set_table_name 'inbox'
end

app/models/outbox.rb
class Outbox < ActiveRecord::Base
  set_table_name 'outbox'
  
  def sent_item
    SentItem.find(self.id)
  end
end

app/models/outbox_multipart.rb
class OutboxMultipart < ActiveRecord::Base
  set_table_name 'outbox_multipart'
end

app/models/pbk.rb
class Pbk < ActiveRecord::Base
  set_table_name 'pbk'
end

app/models/pbk_group.rb
class PbkGroup < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  set_primary_key :IMEI
end

app/models/sent_item.rb
class SentItem < ActiveRecord::Base
  set_table_name "sentitems"
end

app/models/sentitem.rb
class Sentitem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
      @people = Person.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @people }
      end
    end

    # GET /people/1
    # GET /people/1.json
    def show
      @person = Person.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @person }
      end
    end

    # GET /people/new
    # GET /people/new.json
    def new
      @person = Person.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @person }
      end
    end

    # GET /people/1/edit
    def edit
      @person = Person.find(params[:id])
    end

    # POST /people
    # POST /people.json
    def create
      @person = Person.new(params[:person])

      respond_to do |format|
        if @person.save
          format.html { redirect_to @person, notice: 'Person was successfully created.' }
          format.json { render json: @person, status: :created, location: @person }
        else
          format.html { render action: "new" }
          format.json { render json: @person.errors, status: :unprocessable_entity }
        end
      end
    end

    # PUT /people/1
    # PUT /people/1.json
    def update
      @person = Person.find(params[:id])

      respond_to do |format|
        if @person.update_attributes(params[:person])
          format.html { redirect_to @person, notice: 'Person was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @person.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /people/1
    # DELETE /people/1.json
    def destroy
      @person = Person.find(params[:id])
      @person.destroy

      respond_to do |format|
        format.html { redirect_to people_url }
        format.json { head :ok }
      end
    end

    # POST /receive
    #
    # Given a series of phone numbers and a message, it transmits the desired
    # message to all those phone numbers.
    #
    # params: destination_numbers -> A JSON array with the pgone numbers that
    #                                will receive the message
    #         text_decoded -> The message to be sent
    def receive
      @outbox_smses = []
      params[:destination_numbers].each do |dest_num|
        @outbox_smses << Outbox.create(:TextDecoded => params[:text_decoded], 
                                       :DestinationNumber => dest_num, 
                                       :SendingTimeOut => Time.now - 1.days)
      end

      respond_to do |format|
        format.json { render :json => @outbox_smses.to_json }
      end
  end

end

app/controllers/sent_items_controller.rb
class SentItemsController < ApplicationController
  # GET /sentitems/get_statuses
  #
  # Given a series of identifiers for sentitems, returns a JSON dictionary where
  # the keys are the given identifiers and the values are the statuses of such
  # item, or nil if the given id doesn't correspond to any sent item
  #
  # params: item_ids -> An array of identifiers to be searched
  def get_statuses
    statuses = {}
    for id in params[:item_ids]
      sms = SentItem.find_by_ID(id)
      if sms.nil?
        statuses[id] = nil
      else
        statuses[id] = sms.Status
      end
    end

    respond_to do |format|
      format.json{ render :json => statuses.to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LocalReceivingApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Birthdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.first_name %></td>
    <td><%= person.last_name %></td>
    <td><%= person.birthdate %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @person.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @person.last_name %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @person.birthdate %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>